DROP DATABASE IF EXISTS MINIARHIVA;
CREATE DATABASE MINIARHIVA;
USE MINIARHIVA;

CREATE TABLE AUTOSKOLA(
	ID INT NOT NULL PRIMARY KEY,
	NAZIV VARCHAR(50) NOT NULL,
	GRAD VARCHAR(50) NOT NULL	
);

CREATE TABLE POLAZNIK(
	ID INT NOT NULL PRIMARY KEY,
	IME VARCHAR(50) NOT NULL,
	PREZIME VARCHAR(50) NOT NULL, 
	STATUS VARCHAR(50) NOT NULL,
	GODINE DATE NOT NULL,
	ID_SKOLE INT NOT NULL,
	CONSTRAINT fk_autoskola FOREIGN KEY(ID_SKOLE) REFERENCES AUTOSKOLA(ID)
);

CREATE TABLE ISPIT(
	ID_POLAZNIKA INT NOT NULL PRIMARY KEY,
	DATUM DATE NOT NULL,
	TIP_ISPITA VARCHAR(50) NOT NULL,
	BODOVI INT NOT NULL CHECK(BODOVI BETWEEN 0 AND 100),
	ISHOD VARCHAR(50),
	CONSTRAINT fk_polaznik FOREIGN KEY (ID_POLAZNIKA) REFERENCES POLAZNIK(ID)
);
