DROP DATABASE IF EXISTS Test;

DROP DATABASE IF NOT EXISTS Test;

USE Test;

CREATE TABLE IF NOT EXISTS student_mast(
    STUDENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    STUDENT_NAME VARCHAR(50) NOT NULL,
    STUDENT_CLASS VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS student_marks(
    STUDENT_ID INT PRIMARY KEY,
    SUB1 INT CHECK(SUB1 BETWEEN 0 AND 100) DEFAULT 0,
    SUB2 INT CHECK(SUB2 BETWEEN 0 AND 100) DEFAULT 0,
    SUB3 INT CHECK(SUB3 BETWEEN 0 AND 100) DEFAULT 0,   
    SUB4 INT CHECK(SUB4 BETWEEN 0 AND 100) DEFAULT 0, 
    SUB5 INT CHECK(SUB5 BETWEEN 0 AND 100) DEFAULT 0,
    TOTAL INT DEFAULT 0,
    PER_MARKS DECIMAL(5, 2) DEFAULT 0,
    GRADE VARHCAR(20),
    CONSTRAINT fk_studentmst FOREIGN KEY (STUDENT_ID) REFERENCES student_mast(STUDENT_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- DOGADJAJ UNOSENJE STUDENTA U STUDENT_MAST I TREBA AUTOMATSKI DA SE AZURIRA STUDENT_MARKS
-- KAD IMAMO INSERT NEMAMO STARU VREDNOST TJ. OLD

DELIMITER $$
CREATE TRIGGER IF NOT EXISTS DEFAULT_INPUT AFTER INSERT ON student_mast  
FOR EACH ROW 
    BEGIN
        INSERT INTO student_marks(STUDENT_ID)
        VALUES (NEW.STUDENT_ID);
    
    END$$

CREATE TRIGGER SUBJECT_UBDATE BEFORE UPDATE ON student_marks
FOR EACH ROW
    BEGIN 
        -- (5, 0, 0, 0, 0, 0, 0, NULL) --> OLD
        -- (5, 90, ) --> NEW 

        SET NEW.TOTAL = (NEW.SUB1 + NEW.SUB2 + NEW.SUB3 + NEW.SUB4 + NEW.SUB5)/5;
        SET NEW.PER_MARKS = NEW.TOTAL/5;
        IF NEW.PER_MARKS >= 90 THEN 
            SET NEW.GRADE = 'EXCELENT';
        ELSEIF NEW.PER_MARKS >= 75 THEN
            SET NEW.GRADE = 'VERY GOOD'
        ELSIF NEW.PER_MARKS >= 60 THEN 
            SET NEW.GRADE = 'GOOD'
        ELSEIF NEW.PER_MARKS >= 50 THEN 
            SET NEW.GRADE = 'AVERAGE'
        ELSE
            SET NEW.GRADE = 'NOT PROMOTED'
        END IF;
    END$$

CREATE TRIGGER IF NOT EXISTS UPDATE_CLASS 
BEFORE UPDATE ON STUDENT_MAST
FOR EACH ROW
    BEGIN
        DECLARE MSG VARCHAR(100);

        IF NEW.STUDENT_CLASS <= OLD.STUDENT_CLASS THEN
            SET MSG = 'UNEO SI MANJI RAZRED'; 
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = MSG;
        END IF;
    END$$

DELIMITER ;

-- ALTER TABLE STUDENT_MAST 
--     MODIFY COLUMN STUDENT_CLASS INT;

-- ALTER TABLE STUDENT_MAST
--     ADD CHECK(STUDENT_CLASS > 0);

