CREATE DATABASE VEZBA; -- PRAVI BAZU PODATAKA

DROP DATABASE <NAZIV_BAZE>; -- BRISE BAZU COMMENT

--------------------------------------------------

CREATE DATABASE IF NOT EXISTS <NAZIV_BAZE>; -- PRAVI BAZU PODATAKA UKOLIKO ONA VEC NE POSTOJI.COMMENT

DROP DATABASE IF EXISTS <NAZIV_BAZE>; -- OBRISI BAZU UKOLIKO ONA PSTOJI

-------------------------------

