DROP DATABASE IF EXISTS FUDBAL;
CREATE DATABASE FUDBAL CHARACTER SET=UTF8;
USE FUDBAL;

CREATE TABLE TIM(
  SIF_T INT NOT NULL PRIMARY KEY,
  NAZIV VARCHAR(50) NOT NULL,
  MESTO VARCHAR(50) NOT NULL
);

CREATE TABLE UTAKMICA(
  SIF_U INT NOT NULL PRIMARY KEY,
  SIF_T_DOMACI INT NOT NULL,
  SIF_T_GOST INT NOT NULL, 
  KOLO SMALLINT NOT NULL CHECK(KOLO BETWEEN 1 AND 42),
  ISHOD CHAR(1) NOT NULL CHECK(ISHOD IN ('X', '1', '2')),
  GODINA INT NOT NULL,
  CONSTRAINT FK_DOMACI FOREIGN KEY (SIF_T_DOMACI) REFERENCES TIM(SIF_T) ON DELETE CASCADE,
  CONSTRAINT FK_GOST FOREIGN KEY (SIF_T_GOST) REFERENCES TIM(SIF_T) ON DELETE CASCADE,
  CHECK(SIF_T_DOMACI <> SIF_T_GOST),
  UNIQUE(SIF_T_DOMACI, SIF_T_GOST),
);

-- DODAVANJE NOVOG USLOVA NAKON TOGA STO VEC NAPRAVIMO TABELU
-- ALTER TABLE UTAKMICA
-- ADD CHECK(42*41 = (SELECT COUNT(*) FROM UTAKMICA)); -- OVO NE BI TREBALO DA PRODJE JER CHECK NE PODRZAVA PISANJE UPITA
