CREATE TABLE T1(C1 INT, C2 FLOAT);
CREATE TABLE T2(C1 INT, C2 FLOAT);

-- INSTEAD OF OKIDAC SE DEFINISE SAMO NAD POGLEDIMA

CREATE VIEW V5(C1, C2)
AS SELECT DISTINCT C1, C2
FROM T1;

CREATE TRIGGER V5DELETE INSTEAD OF DELETE V5 
REFERENCING OLD AS O
FOR EACH ROW
    BEGIN
        DELETE FROM T1
        WHERE O.C1 = C1 AND O.C2 = C2; 
    END 

