-- materijalizovani pogledi pokupe podatke iz tabele, i heziraju 

CREATE TABLE T1(C1 INT, C2 FLOAT);

INSERT INTO T1
VALUES (4, 6.0),
       (5, 6.0),
       (6. 7.0);

CREATE TABLE T2(C1 INT, C2 FLOAT);

INSERT INTO T2
VALUES (5, 9.0), (5, 4.0), (7, 5.0);

CREATE VIEW V1(VC1) AS 
SELECT C1 
FROM T1;

SELECT *
FROM V1;

INSERT INTO V1 
VALUES (1), (2), (3);

DELETE FROM V1
WHERE VC1 = 2;

UPDATE V1 
SET VC1 = VC1 + 39
WHERE VC1 = 1;

-- ------------------------------------------------------------------------------

CREATE VIEW V2(VC1, VC2)
SELECT C1, C2*C2 
FROM T1;

SELECT * 
FROM V2; 

-- NE MOZEMO OVO DA URADIMO, JER IMAMO NEKU TRANSFORMACIJU 
INSERT INTO V2
VALUES (7, 225.0);

UPDATE V2 
SET VC1 = VC1 + 44;

-- ZBOOG TRANSFORMISANJA VC2 KOLONE, NIJE MOGUCE UPDATE-OVATI KOLONU
UPDATE V2 
SET VC2 = VC2 + 44;

-- PROLAZI = IMA NEKU REFERENCU NA ODGOVARAJUCI RED U BAZNOJ TABELI
DELETE FROM V2 
WHERE VC2 = 75;

-- --------------------------------------------------------------------------------

CREATE VIEW V3(VC1, VC2, VC3)
SELECT T1.C1, T1.C2, T2.C2 
FROM T1 JOIN T2 ON T1.C1 = T2.C1;

SELECT * 
FROM V3; 

-- INSERT, UPDATE, DELETE, MERGE = NE MOGU DA IZVRSIM NIJEDNU OPERACIJU POSTO IMAMO JOIN
DELETE FROM V3 
WHERE VC1 = 5;

-- ----------------------------------------------------------------------------------------


-- NE MOZE DA PRODJE INSERT, JER NE ZNAMO U KOJU TABELU TREBA DA UDJENMO
-- MOGU DA PRODJU, UPDATE I DELETE 
CREATE VIEW V4(VC1, VC2)
SELECT * 
FROM T1 
UNION ALL
SELECT * 
FROM T2 ;

SELECT * 
FROM V4;

-- -----------------------------------------------------------------------------------------

-- SA DISTINCT NE MOZE DA PRODJE INSERT 
-- TAKODJE, NE PROLAZE NI DELETE
CREATE VIEW V5(VC1, VC2)
SELECT DISTINCT *
FROM T1; 

INSERT INTO V5 
VALUES (4, 6.0);

-- -------------------------------------------------------------------------------------------

-- INSTEAD OF TRIGGERI = DEFINISU SE SAMO NAD POGLEDIMA; MODU DA GA DEFINISEM ZA INSERT/UPDATE/DELETE
-- MOZE DA MI KAZE STA CE DA SE IZVRSI NAD TIM POGLEDOM 
-- MOZEMO DA MU KAZEMO KAKO TREBA DA SE PONASA KADA TREBA DA SE URADJI INSERT/UPDATE/DELETE

-- KADA IMAMO DELETE IMAMO SAMO OLD!

--#SET TERMINATOR @ 
CREATE TRIGGER V5_DELETE 
INSTEAD OF DELETE ON V5 
REFERENCING OLD AS O 
FOR EACH ROW MODE DB2SQL  
    BEGIN ATOMIC 
        DELETE FROM T1 
        WHERE C1 = O.VC1 AND C2 = O.VC2;
    END@

--#SET TERMINATOR ;

-- DROP TABLE T1;
-- DROP TABLE T2;
-- DROP VIEW V1;
-- DROP VIEW V2;